name: CD - Deploy to Docker Hub

on:
  workflow_run:
    workflows: ["CI - Build & Test"]
    types:
      - completed
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu:latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true  # Push in CD
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crud-php-app:latest
